export default function compliments() {
  return [
    "je weet altijd waar de sokken van iedereen liggen.",
    "je kunt beter multitasken dan tien laptops tegelijk.",
    "je bent de koningin van knuffels.",
    "je kunt van restjes zo een vijfsterrendiner maken.",
    "je weet altijd wat ik bedoel, zelfs als ik alleen maar 'uhh' zeg.",
    "je bent sneller dan Google als ik iets kwijt ben.",
    "je weet precies hoeveel melk er nog in het pak zit zonder te kijken.",
    "je weet altijd welke jas ik moet aandoen (en je hebt meestal gelijk).",
    "je bent beter in multitasken dan een octopus met acht armen.",
    "je geeft knuffels die stress doen verdwijnen.",
    "je hebt altijd een oplossing, zelfs voor kapotte (l)ego.",
    "je maakt een regenachtige dag alsnog gezellig.",
    "je bent de uitvinder van 'nog één stukje chocola dan'.",
    "je kunt honderd dingen tegelijk doen zonder je thee te vergeten.",
    "je bent een wandelende agenda (zonder foutjes).",
    "je kunt alles repareren met plakband en liefde.",
    "je hebt de beste inside jokes. (🎵 laaaaand van maas en waal 🎵)",
    "je laat de wasmachine klinken als muziek (bijna).",
    "je bent de kampioen van spelletjesavond (ook als je verliest).",
    "je hebt altijd de leukste verhalen van vroeger.",
    "je hebt meer geduld dan een verkeerslicht.",
    "je kunt dingen vinden die al dagen zoek zijn.",
    "je hebt altijd tijd voor een kopje thee.",
    "je kunt iemand blij maken met alleen een blik.",
    "je weet hoe je chaos omtovert in gezelligheid.",
    "je kunt een verjaardag onvergetelijk maken.",
    "je hebt altijd een paraplu paraat.",
    "je bent de beste raadgever, zelfs als ik niet luister.",
    "je weet hoe je gewone dagen speciaal maakt.",
    "je kunt iedereen aan het lachen maken, zelfs de chagrijnige buurman.",
    "je bent een held in puzzels oplossen (zelfs levenspuzzels).",
    "je hebt meer energie dan drie kopjes koffie.",
    "je weet altijd het juiste antwoord op lastige vragen.",
    "je kunt zelfs van opruimen een feestje maken.",
    "je hebt de beste slaapliedjes.",
    "je hebt betere grappen dan Peter Pannenkoek.",
    "je weet altijd wat er in de koelkast ontbreekt.",
    "je bent een ninja in cadeautjes verstoppen.",
    "je hebt de beste timing voor knuffels.",
    "je weet altijd waar de afstandsbediening ligt.",
    "je kunt sokken vouwen als een pro.",
    "je bent een wandelende weer-app (en hebt meestal gelijk).",
    "je maakt de beste pannekoekenstapels.",
    "je kunt beter onderhandelen dan een topadvocaat.",
    "je weet precies hoe je iemand gerust moet stellen.",
    "je bent grappiger dan alle moppenboekjes samen.",
    "je kunt van niks een feestje maken.",
    "je hebt een superkracht voor troostwoorden.",
    "je weet altijd een creatieve oplossing.",
    "je bent een pro in selfies maken.",
    "je weet hoe je ons allemaal samenbrengt.",
    "je hebt een radar voor rommel die wij niet zien.",
    "je maakt de lekkerste kip met romige saus.",
    "je kunt de leukste stemmen doen bij het voorlezen.",
    "je weet altijd hoe je de sfeer redt.",
    "je weet precies hoe je iemand blij kunt verrassen.",
    "je hebt de beste feestdecoraties.",
    "je bent een meester in cadeautjes uitkiezen.",
    "je kunt multitasken terwijl je lacht.",
    "je hebt de beste dansfeestjes in de keuken.",
    "je weet altijd waar de pleisters liggen.",
    "je bent beter in knutselen dan Pinterest.",
    "je hebt de beste inside jokes.",
    "je bent een expert in geheimen bewaren.",
    "je hebt altijd een grapje achter de hand.",
    "je hebt altijd een slim trucje klaar.",
    "je weet hoe je iemand super speciaal laat voelen.",
    "je weet precies hoe je ruzies oplost.",
    "je hebt altijd een briljant idee klaar.",
    "je kunt lachen om je eigen grappen (en dat maakt ze beter).",
    "je hebt altijd een plan B (en C).",
    "je weet hoe je elke dag gezellig maakt.",
    "je hebt de leukste verrassingstrucjes.",
    "je kunt iemand blij maken met een simpele blik (of berichtje)."
  ]

}

