export default function compliments() {
  return [
    "je weet altijd waar de sokken van iedereen liggen.",
    "je maakt de lekkerste tosti’s van de wereld.",
    "je kunt beter multitasken dan tien laptops tegelijk.",
    "je hebt altijd tissues op zak precies op het juiste moment.",
    "je bent de koningin van knuffels.",
    "je kunt zelfs van restjes een vijfsterrendiner maken.",
    "je weet altijd wat ik bedoel, zelfs als ik alleen maar 'uhh' zeg.",
    "je bent sneller dan Google als ik iets kwijt ben.",
    "je hebt de beste dansmoves in de woonkamer.",
    "je kunt mopjes vertellen die zelfs papa laat lachen.",
    "je hebt de gave om wifi te laten werken door er alleen maar naar te kijken.",
    "je weet precies hoeveel melk er nog in het pak zit zonder te kijken.",
    "je bent de beste taxichauffeur zonder betaald te worden.",
    "je hebt altijd snoepjes verstopt op magische plekken.",
    "je kunt een knoop uit veters halen die onmogelijk leek.",
    "je weet altijd welke jas ik moet aandoen (en je hebt meestal gelijk).",
    "je bent beter in multitasken dan een octopus met acht armen.",
    "je kookt pasta net zo lekker als in Italië.",
    "je geeft knuffels die stress doen verdwijnen.",
    "je hebt altijd een oplossing, zelfs voor kapotte lego.",
    "je maakt een regenachtige dag alsnog gezellig.",
    "je bent de uitvinder van 'nog één koekje dan'.",
    "je weet hoe je iedereen aan het lachen krijgt.",
    "je hebt magische helende kusjes.",
    "je kunt honderd dingen tegelijk doen zonder je koffie te vergeten.",
    "je bent een wandelende agenda (zonder foutjes).",
    "je kunt alles repareren met plakband en liefde.",
    "je hebt de beste inside jokes met ons.",
    "je laat de wasmachine klinken als muziek (bijna).",
    "je bent de kampioen van spelletjesavond (ook als je verliest).",
    "je hebt altijd de leukste verhalen van vroeger.",
    "je hebt meer geduld dan een verkeerslicht.",
    "je weet precies wat er ontbreekt in een recept.",
    "je kunt dingen vinden die al dagen zoek zijn.",
    "je hebt een zesde zintuig voor onzinverhalen.",
    "je bent een expert in knopen ontwarren.",
    "je hebt altijd tijd voor een kopje thee.",
    "je kunt iemand blij maken met alleen een blik.",
    "je hebt de beste playlist tijdens autoritten.",
    "je weet hoe je chaos omtovert in gezelligheid.",
    "je hebt humor die nooit oud wordt.",
    "je kunt een verjaardag onvergetelijk maken.",
    "je hebt altijd een paraplu paraat.",
    "je bent de beste raadgever, zelfs als ik niet luister.",
    "je weet hoe je van gewone dagen speciale dagen maakt.",
    "je kunt iedereen aan het lachen maken, zelfs de chagrijnige buurman.",
    "je bent een held in puzzels oplossen (levenspuzzels ook).",
    "je hebt de beste opmerkingen bij films.",
    "je hebt meer energie dan drie kopjes koffie.",
    "je weet altijd het juiste antwoord op lastige vragen.",
    "je kunt zelfs van opruimen een feestje maken.",
    "je hebt de beste slaapliedjes (ook al zing je vals).",
    "je bent beter in grappen dan TikTok.",
    "je weet altijd wat er in de koelkast ontbreekt.",
    "je bent een ninja in cadeautjes verstoppen.",
    "je hebt de beste timing voor knuffels.",
    "je weet altijd waar de afstandsbediening ligt.",
    "je kunt sokken vouwen als een pro.",
    "je bent een wandelende weer-app (en hebt meestal gelijk).",
    "je maakt de beste pannekoekenstapels.",
    "je kunt beter onderhandelen dan een topadvocaat.",
    "je weet precies hoe je iemand gerust moet stellen.",
    "je bent grappiger dan alle moppenboekjes samen.",
    "je kunt van niks een feestje maken.",
    "je hebt altijd snacks bij je op de juiste momenten.",
    "je hebt een superkracht voor troostwoorden.",
    "je bent slimmer dan je telefoon.",
    "je weet altijd een creatieve oplossing.",
    "je bent een pro in selfies maken.",
    "je weet hoe je ons allemaal samenbrengt.",
    "je bent de koningin van het bedtijdritueel.",
    "je hebt een radar voor rommel die wij niet zien.",
    "je maakt betere soep dan oma (sorry oma).",
    "je kunt de leukste stemmen doen bij het voorlezen.",
    "je weet altijd hoe je de sfeer redt.",
    "je hebt een lach die aanstekelijk is.",
    "je bent beter dan Google Maps.",
    "je weet precies hoe je iemand blij kunt verrassen.",
    "je hebt de beste feestdecoraties.",
    "je bent een meester in cadeautjes uitkiezen.",
    "je weet hoe je iedereen geruststelt tijdens onweer.",
    "je kunt multitasken terwijl je lacht.",
    "je hebt de beste dansfeestjes in de keuken.",
    "je bent een kampioen in koekjes bakken.",
    "je weet altijd waar de pleisters liggen.",
    "je bent beter in knutselen dan Pinterest.",
    "je hebt de beste inside jokes.",
    "je bent een expert in geheimen bewaren.",
    "je weet hoe je iedereen aan het zingen krijgt.",
    "je hebt altijd een grapje achter de hand.",
    "je weet hoe je zelfs in files de sfeer leuk houdt.",
    "je bent een wandelende snoepautomaat.",
    "je hebt altijd een slim trucje klaar.",
    "je weet hoe je iemand super speciaal laat voelen.",
    "je bent een kampioen in high fives.",
    "je hebt de beste verhaaltjes voor het slapengaan.",
    "je weet precies hoe je ruzies oplost.",
    "je bent beter in karaoke dan de tv zelf.",
    "je hebt altijd een briljant idee klaar.",
    "je kunt lachen om je eigen grappen (en dat maakt ze beter).",
    "je hebt altijd een plan B (en C).",
    "je weet hoe je elke dag gezellig maakt.",
    "je hebt de leukste verrassingstrucjes.",
    "je kunt iemand blij maken met een simpele blik."
  ]

}

